# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
  - stage: step1
    jobs:
      - job: checkout_code_from_repo
        displayName: 'Checkout code from repo'
        strategy:
          matrix:
            Server81:
              AGENT_NAME: 'Agent-server-81'
        pool:
          name: 'EFormCI'
          demands:
          - agent.name -equals $(AGENT_NAME)
        steps:
          - checkout: 'none'
            displayName: 'Checkout code from repo'
          - script: |
              echo ##[command]
              cd C:\\agents\\_work\\3\\s
              echo ##[command]
              git pull origin master
              echo ##[command]
              npm run build_test
            displayName: 'npm install and build'