# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- sprint-20

pool:
  name: 'Eform_UAT'

steps:
- checkout: 'none'
  displayName: 'checkout code from repo'
- script: |
    echo ##[command]
    cd C:\\agents\\_work\\4\\s
    echo ##[command]
    rmdir C:\\agents\\_work\\4\\s\\dist
    echo ##[command]
    git status
    echo ##[command]
    git pull
    echo ##[command]
    npm run build_test
  displayName: 'npm install and build'
- script: |
    echo ##[command]
    rmdir C:\\agents\\_work\\3\\s\\Application\\EForm\\static
    echo ##[command]
    xcopy C:\\agents\\_work\\4\\s\\dist\\production C:\\agents\\_work\\3\\s\\Application\\EForm /E /Y