# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- sprint-20

pool:
  name: 'Default'

steps:
- checkout: 'none'
  displayName: 'checkout code from repo'
- script: |
    echo ##[command]
    cd C:\\agents\\_work\\2\\s
    echo ##[command]
    rmdir C:\\agents\\_work\\2\\s\\dist
    echo ##[command]
    git status
    echo ##[command]
    git pull
    echo ##[command]
    npm run build_test
  displayName: 'npm install and build'
- script: |
    echo ##[command]
    rmdir E:\\Projects\\eform\\dev_ci\\static
    echo ##[command]
    xcopy C:\\agents\\_work\\2\\s\\dist\\production E:\\Projects\\eform\\dev_ci /E /Y
