# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  name: 'EFormCI'

stages:
  - stage: copy_file_server_81
    jobs:
      - job: 
        steps:
          - checkout: 'none'
            displayName: 'Checkout code from repo'
          - script: |
              echo ##[command]
              rmdir /s D:\\Project\\APP\\static
              echo ##[command]
              xcopy C:\\agents\\_work\\3\\s\\dist\\production D:\\Project\\APP /E /Y
  - stage: copy_file
    jobs:
      - job: copy_file_from_server_81
        displayName: 'Copy file from server 81'
        strategy:
          matrix:
            Server82:
              AGENT_NAME: 'Agent-server-82'
            Server83:
              AGENT_NAME: 'Agent-server-83'
            Server84:
              AGENT_NAME: 'Agent-server-84'
        pool:
          name: 'EFormCI'
          demands:
          - agent.name -equals $(AGENT_NAME)
        steps:
        - checkout: 'none'
          displayName: 'Checkout code from repo'
        - script: |
            echo ##[command]
            cd  C:\\agents\\_work\\BAT_TO_COPY
            echo ##[command]
            copy.bat
