--- Deploy 12/01/2023
update MasterDatas set Code = 'INITIALASSESSMENTSHORTCONFIRM_RS_USERRECIVED' 
where Code = 'INITIALASSESSMENTSHORTCONFIRM_RS_USERCREATED'

--- Bảng kiểm chuẩn bị ra viện
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đã bàn giao đúng chủng loại, đủ số lượng thuốc cho người bệnh theo đơn ra viện?',N'Have handover of correct types and quantity of medication to patient been completed based on discharge prescription?',N'IPDDPCN117',N'IPDDPCNDIF',N'A03_046_050919_VE',N'1',N'130',N'Label',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Rồi/Có',N'Completed/Yes',N'IPDDPCN118',N'IPDDPCN117',N'A03_046_050919_VE',N'2',N'131',N'Radio',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không áp dụng',N'NA',N'IPDDPCN119',N'IPDDPCN117',N'A03_046_050919_VE',N'2',N'132',N'Radio',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ghi chú (nếu có)',N'Notes (if any)',N'IPDDPCN120',N'IPDDPCN117',N'A03_046_050919_VE',N'2',N'133',N'Text',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đã hoàn thiện GDSK tất cả các thuốc ra viện? (Tham chiếu “Phiếu GDSK cho người bệnh và thân nhân”)',N'Complete education on home medication (Refer to “Patient and Family Education Form”)',N'IPDDPCN121',N'IPDDPCNDIF',N'A03_046_050919_VE',N'1',N'134',N'Label',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Rồi/Có',N'Completed/Yes',N'IPDDPCN122',N'IPDDPCN121',N'A03_046_050919_VE',N'2',N'135',N'Radio',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không áp dụng',N'NA',N'IPDDPCN123',N'IPDDPCN121',N'A03_046_050919_VE',N'2',N'136',N'Radio',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Ghi chú (nếu có)',N'Notes (if any)',N'IPDDPCN124',N'IPDDPCN121',N'A03_046_050919_VE',N'2',N'137',N'Text',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chức danh người trực tiếp thực hiện',N'Chức danh người trực tiếp thực hiện',N'IPDDPCN125',N'IPDDPCNDIF',N'A03_046_050919_VE',N'1',N'138',N'Label',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bác sĩ',N'Doctor',N'IPDDPCN126',N'IPDDPCN125',N'A03_046_050919_VE',N'2',N'139',N'Radio',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Điều dưỡng',N'Nurse',N'IPDDPCN127',N'IPDDPCN125',N'A03_046_050919_VE',N'2',N'140',N'Radio',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dược sỹ',N'Pharmacist',N'IPDDPCN128',N'IPDDPCN125',N'A03_046_050919_VE',N'2',N'141',N'Radio',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chức danh người trực tiếp thực hiện',N'Chức danh người trực tiếp thực hiện',N'IPDDPCN129',N'IPDDPCNDIF',N'A03_046_050919_VE',N'1',N'142',N'Label',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bác sĩ',N'Doctor',N'IPDDPCN130',N'IPDDPCN129',N'A03_046_050919_VE',N'2',N'143',N'Radio',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Điều dưỡng',N'Nurse',N'IPDDPCN131',N'IPDDPCN129',N'A03_046_050919_VE',N'2',N'144',N'Radio',N'',N'',N'',N'', '2');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Dược sỹ',N'Pharmacist',N'IPDDPCN132',N'IPDDPCN129',N'A03_046_050919_VE',N'2',N'145',N'Radio',N'',N'',N'',N'', '2');