Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nơi giới thiệu',N'Referred by',N'OPDOENPT603',N'OPDOEN',N'OPDOEN',N'1',N'603',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cơ quan y tế',N'Hospitals',N'OPDOENPT604',N'OPDOENPT603',N'OPDOEN',N'2',N'604',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tự đến',N'By themselves',N'OPDOENPT605',N'OPDOENPT603',N'OPDOEN',N'2',N'605',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Cơ quan y tế',N'Hospitals',N'OPDOENPT606',N'OPDOEN',N'OPDOEN',N'1',N'606',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chẩn đoán của nơi giới thiệu',N'Referral center',N'OPDOENPT607',N'OPDOENPT606',N'OPDOEN',N'2',N'607',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chẩn đoán của nơi giới thiệu',N'Referral center',N'OPDOENPT608',N'OPDOENPT606',N'OPDOEN',N'2',N'608',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không khai thác được',N'Nil',N'OPDOENPT609',N'OPDOENPT606',N'OPDOEN',N'2',N'609',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đã xử lý (thuốc, chăm sóc)',N'Treatment (medication, care)',N'OPDOENPT610',N'OPDOEN',N'OPDOEN',N'1',N'610',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Không',N'No',N'OPDOENPT611',N'OPDOENPT610',N'OPDOEN',N'2',N'611',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Có',N'Yes',N'OPDOENPT612',N'OPDOENPT610',N'OPDOEN',N'2',N'612',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đã xử lý (thuốc, chăm sóc)',N'Treatment (medication, care)',N'OPDOENPT613',N'OPDOENPT610',N'OPDOEN',N'2',N'613',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tình trạng người bệnh ra viện',N'Patient status at discharge',N'OPDOENPT614',N'OPDOEN',N'OPDOEN',N'1',N'614',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khỏi',N'Cured',N'OPDOENPT615',N'OPDOENPT614',N'OPDOEN',N'2',N'615',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Đỡ, giảm',N'Improved',N'OPDOENPT616',N'OPDOENPT614',N'OPDOEN',N'2',N'616',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Chưa thay đổi',N'Unchanged',N'OPDOENPT617',N'OPDOENPT614',N'OPDOEN',N'2',N'617',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Nặng hơn',N'Worsened',N'OPDOENPT618',N'OPDOENPT614',N'OPDOEN',N'2',N'618',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Khác',N'Others',N'OPDOENPT619',N'OPDOENPT614',N'OPDOEN',N'2',N'619',N'Radio',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tình trạng người bệnh ra viện',N'Patient status at discharge',N'OPDOENPT620',N'OPDOENPT614',N'OPDOEN',N'2',N'620',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Tiền sử bệnh',N'Tiền sử bệnh',N'OPDOENPT621',N'OPDOEN',N'OPDOEN',N'1',N'621',N'Label',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Gia đình',N'Family history',N'OPDOENPT622',N'OPDOENPT621',N'OPDOEN',N'2',N'622',N'Text',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Báo bác sĩ điều trị',N'Inform attending physician',N'IPDIAAUITV8IAPNEW',N'IPDIAAUITV8',N'IPDIAAU',N'2',N'541',N'Checkbox',N'',N'',N'',N'', '1');


Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Giám đốc',N'Giám đốc',N'OUTPATIENT_DIR',N'A01_252_221222_V',N'A01_252_221222_V',N'1',N'1',N'ConfirmForm',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bác sỹ khám bệnh',N'Bác sỹ khám bệnh',N'OUTPATIENT_PHY',N'A01_252_221222_V',N'A01_252_221222_V',N'1',N'2',N'ConfirmForm',N'',N'',N'',N'', '1');
Insert into MasterDatas  (Id, CreatedAt, UpdatedAt, IsDeleted,ViName, EnName, Code, [Group], Form, [Level], [Order], DataType, Note, IsReadOnly,Data, Clinic, [Version]) values (NEWID(), GETDATE(), GETDATE(), 'False', N'Bác sỹ điều trị',N'Bác sỹ điều trị',N'OUTPATIENT_PHY_SUMMARY',N'OUTPATIENT_PHY_SUMMARY',N'OUTPATIENT_PHY_SUMMARY',N'1',N'1',N'ConfirmForm',N'',N'',N'',N'', '1');